### ISSUE TITLE
Get-MSSQLLinkPasswords.ps1 overwritten by Get-LinkedServer.ps1 

### ISSUE THREAD

**Issue by paulfwhite** [imajaydwivedi/SQLDBATools#6]
I think the source for Get-MSSQLLinkPasswords.ps1 has been overwritten by Get-LinkedServer.ps1 
I'm new to Github, but I thin the last change in Feb introduced a changes to several scripts.  You may need to wind back to October.

Paul

**Comment by imajaydwivedi** [comment]
Thanks, @paulfwhite for notifying me. I'll make the necessary changes.
